spring:
  application:
    name: Marathon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Marathon
    username: root
    password: 123456
  mvc:
    static-path-pattern: /files/**
  web:
    resources:
      static-locations: file:uploads/
logging:
  level:
    com.example.marathon.mapper: debug
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.marathon.table,com.example.marathon.pojo
